# -*- coding: utf-8 -*-
"""modeloProbabilistico

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KcrejQav28MkFZes30bBRvzCSOhYGEJ-
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import OrdinalEncoder

data = [
['infantil','miopia','não','reduzida','nenhuma'],
['infantil','miopia','sim','normal','gelatinosa'],
['infantil','hipermetropia','não','normal','gelatinosa'],
['infantil','hipermetropia','sim','normal','dura'],
['adolescente','miopia','não','reduzida','gelatinosa'],
['adolescente','miopia','sim','reduzida','nenhuma'],
['adolescente','miopia','não','normal','dura'],
['adolescente','hipermetropia','não','reduzida','gelatinosa'],
['adolescente','hipermetropia','sim','normal','dura'],
['adulto','miopia','não','normal','gelatinosa'],
['adulto','miopia','sim','normal','dura'],
['adulto','miopia','sim','normal','gelatinosa'],
['adulto','hipermetropia','não','reduzida','nenhuma'],
['adulto','hipermetropia','sim','normal','gelatinosa'],
['adulto','hipermetropia','não','normal','gelatinosa']
]

df = pd.DataFrame(data, columns=['idade','diagnostico','astigmatismo','lacrimal','classe'])

X = df[['idade','diagnostico','astigmatismo','lacrimal']]
y = df['classe']

encoder = OrdinalEncoder()
X_enc = encoder.fit_transform(X)

x_input = ['infantil','hipermetropia','não','reduzida']

alpha = 1
classes = y.unique()
N = len(df)
K = len(classes)

probs = {}

for c in classes:
    df_c = df[df['classe'] == c]
    Nc = len(df_c)
    prior = (Nc + alpha) / (N + K)
    likelihood = 1
    for col, val in zip(X.columns, x_input):
        count = len(df_c[df_c[col] == val])
        k = df[col].nunique()
        prob = (count + alpha) / (Nc + k)
        likelihood *= prob
    probs[c] = prior * likelihood

total = sum(probs.values())
probs_norm = {k: v/total for k, v in probs.items()}

print("Probabilidades normalizadas:")
for k, v in probs_norm.items():
    print(f"{k}: {v*100:.2f}%")

print("\nClasse prevista:", max(probs_norm, key=probs_norm.get))